# Generated by Django 4.1.6 on 2023-02-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=5096)),
                ('type', models.CharField(max_length=64)),
                ('open_at', models.DateField()),
                ('due_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=5096)),
                ('time_spent', models.TimeField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='question')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='unit')),
            ],
        ),
    ]
