# Generated by Django 4.1.6 on 2023-02-12 19:26

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('A-3/4', 'A-3/4'), ('A-7/8', 'A-7/8'), ('B-3/4', 'B-3/4'), ('B-7/8', 'B-7/8')], max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=16384)),
                ('opens_on', models.DateField()),
                ('due_on', models.DateField()),
                ('pre_requisite', models.IntegerField()),
                ('type', models.CharField(choices=[('Test', 'Test'), ('Experiment', 'Experiment')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', shortuuid.django_fields.ShortUUIDField(alphabet='012345679', length=4, max_length=4, prefix='', unique=True)),
                ('signed', models.BooleanField(null=True)),
                ('type', models.CharField(choices=[('Experimental', 'Experimental'), ('Control', 'Control')], max_length=12)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=16384)),
                ('submitted_on', models.DateField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='core.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=16384)),
                ('time_spent', models.IntegerField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.unit')),
            ],
        ),
    ]
