# Generated by Django 4.1.6 on 2023-02-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Pretest', 'Pretest'), ('Normal', 'Normal'), ('Posttest', 'Posttest')], max_length=64),
        ),
    ]
