# Generated by Django 4.1.6 on 2023-02-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='unit_id',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='answer',
            name='time_spent',
            field=models.IntegerField(),
        ),
    ]
