# Generated by Django 4.1.6 on 2023-02-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_question_pre_requisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pre_requisite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
