# Generated by Django 4.1.6 on 2023-02-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_question_id_answer_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='unit',
            new_name='unit_id',
        ),
    ]
