# Generated by Django 4.1.6 on 2023-02-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_question_answer_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default='def', max_length=16384),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=16384),
        ),
    ]
