# Generated by Django 4.1.6 on 2023-02-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_question_pre_requisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.classroom'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('Experimental', 'Experimental'), ('Control', 'Control'), ('Test', 'Test')], max_length=12),
        ),
    ]
