# Generated by Django 4.1.6 on 2023-02-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_due_at_question_due_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_spent',
            field=models.IntegerField(null=True),
        ),
    ]
