# Generated by Django 4.1.6 on 2023-02-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_answer_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreview',
            name='content',
            field=models.TextField(max_length=16384),
        ),
    ]
